[ui]
width = 1200
height = 800
language = "zh_tw"

[epub]
folder_path = ""
subfolder = false

[glossary]
folder_path = ""
subfolder = false

[translation_tag]
content = "{content}"
glossary = "{glossary}"
history = "{history}"

[glossary_tag]
source_text = "{source_text}"
translation = "{translation}"
annotation = "{annotation}"

[prompt_options]
dynamic_glossary = true