[ui]
window_title = "epub-batch-translator"
language = "zh_tw"
width = 1200
height = 840
tabs_index = 0

[epub]
folder_path = ""
options = ""
subfolder = false

[glossary]
folder_path = ""
options = ""
subfolder = false

[vllm_parameter_file]
folder_path = "./user_data/vllm_parameter"
options = ""

[prompt_parameter_file]
folder_path = "./user_data/prompt_parameter"
options = ""

[prompt_options]
dynamic_glossary = true

[translation_tag]
content = "{content}"
glossary = "{glossary}"
history = "{history}"

[glossary_tag]
source_text = "{source_text}"
translation = "{translation}"
annotation = "{annotation}"