[ui]
width = 1080
height = 840
language = "zh_tw"

[epub]
folder_path = ""
options = ""
subfolder = false

[glossary]
folder_path = ""
options = ""
subfolder = false

[translation_tag]
content = "{content}"
glossary = "{glossary}"
history = "{history}"

[glossary_tag]
source_text = "{source_text}"
translation = "{translation}"
annotation = "{annotation}"

[prompt_options]
dynamic_glossary = true