[main_page]
select_all_epub_flies = "ALL epub"
open_epub_folder = "open folder"
language = "language"

[processing_stage]
no_task = "There are no ongoing tasks."
auto_processing = "auto"
extract_content = "extract content"
calculate_similarity = "calculate similarity"
content_chunking = "content chunking"
translate = "translate"
alignment_check = "alignment check"
replace_translation = "replace translation"

[prompt_tab]
tab_name = "prompt"

[llm_api_tab]
tab_name = "LLM API"

[vllm_tab]
tab_name = "vLLM"