[menu_bar]
language = "language"
about = "about"

[menu_bar.settings_menu]
menu_name = "settings"
reset_ui = "reset ui"

[epub_widget]
select_all_epub_flies = "-- ALL epub --"
open_epub_folder = "open folder"
subfolder = "subfolder"

[processing_stage]
select_translator = "translator"
no_task = "There are no ongoing tasks."
auto_processing = "auto"
extract_content = "extract content"
calculate_similarity = "calculate similarity"
content_chunking = "content chunking"
translate = "translate"
alignment_check = "alignment check"
replace_translation = "replace translation"

[prompts_area]
translation_prompt = "translation prompt"
translation_prompt_example = """
You are an expert Chinese novel translator, skilled at translating Chinese into English in a corresponding style without compromising the original meaning or intent.
Please use the glossary during translation to translate specific original terms into their designated equivalents, and refer to the notes provided in the glossary.
Please refer to the history during translation to ensure smooth coherence between the preceding and following text.

# History
{history}

# Glossary
{glossary}

# Chinese Source Text
{content}"""
glossary_prompt = "glossary prompt"
glossary_prompt_example = "<Source Text>{source_text} <Translation>{translation} <Annotation>{annotation}"

[prompts_area.translation_tag]
content = "Content Tag"
glossary = "Glossary Tag"
history = "History Tag"

[prompts_area.glossary_tag]
source_text = "Source Text Tag"
translation = "Translation Tag"
annotation = "Annotation Tag"

[llm_api_tab]
tab_name = "LLM API"

[vllm_tab]
tab_name = "vLLM"

[reset_ui_message]
title = "Warning!"
message = """
This will directly delete saved user settings, causing window size, language, and other settings to revert to default values.

A restart of the application is required for the changes to take effect."""
confirm = "confirm and restart"
cancel = "cancel"

[about_message]
title = "about"
message = """
Version: v0.0.alpha
<br><br>Dev: <a href="https://github.com/Riyuechang">Riyuechang</a>
<br><br>Repo: <a href="https://github.com/Riyuechang/epub-batch-translator">epub-batch-translator</a>"""
confirm = "confirm"