[main_page]
select_all_epub_flies = "所有 epub"
open_epub_folder = "選擇資料夾"
language = "語言"

[processing_stage]
no_task = "沒有正在進行的任務"
auto_processing = "自動處理"
extract_content = "提取內容"
calculate_similarity = "計算相似度"
content_chunking = "內容分塊"
translate = "翻譯"
alignment_check = "對齊檢查"
replace_translation = "替換翻譯"

[prompt_tab]
tab_name = "提示詞"

[llm_api_tab]
tab_name = "語言模型 API"

[vllm_tab]
tab_name = "vLLM"