[menu_bar]
language = "語言"
about = "關於"

[menu_bar.settings_menu]
menu_name = "設定"
reset_ui = "重置 UI"

[epub_widget]
select_all_epub_flies = "-- 所有 epub --"
open_epub_folder = "選擇資料夾"
subfolder = "子資料夾"

[processing_stage]
select_translator = "翻譯器"
no_task = "沒有正在進行的任務"
auto_processing = "自動處理"
extract_content = "提取內容"
calculate_similarity = "計算相似度"
content_chunking = "內容分塊"
translate = "翻譯"
alignment_check = "對齊檢查"
replace_translation = "替換翻譯"

[prompts_area]
translation_prompt = "翻譯提示詞"
translation_prompt_example = """
你是一個英文小說翻譯專家，擅長在不破壞原文想傳達的事物下，將英文以對應的風格翻譯成繁體中文。
請在翻譯時使用術語表，將指定的原文翻譯成對應譯文，並參考術語表提供的註解進行翻譯。
請在翻譯時參考歷史紀錄，讓前後文可以通順銜接。

# 歷史紀錄
{history}

# 術語表
{glossary}

# 英文原文
{content}"""
glossary_prompt = "術語表提示詞"
glossary_prompt_example = "<原文>{source_text} <譯文>{translation} <註解>{annotation}"

[prompts_area.translation_tag]
content = "內容標籤"
glossary = "術語表標籤"
history = "歷史標籤"

[prompts_area.glossary_tag]
source_text = "原文標籤"
translation = "譯文標籤"
annotation = "註解標籤"

[llm_api_tab]
tab_name = "語言模型 API"

[vllm_tab]
tab_name = "vLLM"

[reset_ui_message]
title = "警告！"
message = """
這將直接刪除已儲存的使用者設定，導致視窗大小、語言和其他設定恢復成預設值。

需要重新啟動應用程式才會生效"""
confirm = "確認並重啟"
cancel = "取消"

[about_message]
title = "關於"
message = """
版本: v0.0.alpha
<br><br>開發者: <a href="https://github.com/Riyuechang">Riyuechang</a>
<br><br>儲存庫: <a href="https://github.com/Riyuechang/epub-batch-translator">epub-batch-translator</a>"""
confirm = "確認"